# Generated by Django 2.2.12 on 2022-11-25 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentfile', models.FileField(upload_to='uploads/')),
                ('Treestructure', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('autograder', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('deadline', models.DateTimeField()),
                ('upload_type', models.CharField(choices=[('.zip', '.zip'), ('.tgz', '.tgz'), ('.cpp', '.cpp'), ('.py', '.py'), ('.pdf', '.pdf'), ('.sh', '.sh')], default='.py', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('prof', models.CharField(default='Kavi', max_length=50)),
                ('assignments', models.ManyToManyField(to='users.assignments')),
            ],
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(blank=True, max_length=200, null=True)),
                ('prof', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentsubmissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('solution', models.FileField(upload_to='uploads/')),
                ('file_name', models.CharField(default='x', max_length=300)),
                ('feedback', models.CharField(max_length=300)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100)),
                ('identity', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('assistant', 'assistant')], default='student', max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(default='pbhavana5454@gmail.com', max_length=254)),
                ('courses_registered', models.ManyToManyField(default='', to='users.courses')),
                ('messages', models.ManyToManyField(to='users.messages')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='u', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignments',
            name='s',
            field=models.ManyToManyField(to='users.studentsubmissions'),
        ),
    ]
