# Generated by Django 4.1.2 on 2022-11-21 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
