# Generated by Django 3.2.12 on 2022-11-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_assignments_file_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='file_type',
            new_name='upload_type',
        ),
    ]
